[server]
host = "0.0.0.0"
port = "8090"
log_level = "INFO"

[runtime]
type = "docker"
execd_image = "opensandbox/execd:v1.0.7"

[egress]
image = "opensandbox/egress:v1.0.3"

[docker]
network_mode = "bridge"
host_ip = "host.docker.internal"
